DROP USER IF EXISTS Ulna;
DROP DATABASE IF EXISTS media;

CREATE USER Ulna;
CREATE DATABASE media OWNER Ulna;
CREATE TYPE kindOf AS ENUM('poésie', 'roman', 'théatre', 'épistolaire', 'BD', 'comics', 'dvd', 'cd', 'vinyle', 'livre diver', 'revue');

DROP TABLE IF EXISTS Livre;
CREATE TABLE Livre(
	title VARCHAR(256) UNIQUE NOT NULL PRIMARY KEY,
	image BYTEA NOT NULL,
	release_date TIMESTAMP NOT NULL,
	descrition TEXT NOT NULL,
	author VARCHAR(64) NOT NULL,
	kind kindOf NOT NULL DEFAULT 'livre diver',
	isbn VARCHAR(64) UNIQUE,
	loan_date TIMESTAMP,
	edition VARCHAR(128),
	borrower INT,
	email VARCHAR(64) NOT NULL,
	birth_date TIMESTAMP NOT NULL,
	adresse TEXT NOT NULL,
	mdp VARCHAR(256) NOT NULL,
	is_verified BOOLEAN NOT NULL
	CONSTRAINT fk_Users
		FOREIGN KEY(borrower) 
			REFERENCES Users(id),
		FOREIGN KEY(author)
			REFERENCES Auteur(uuid)
	);

DROP TABLE IF EXISTS Users;
CREATE TABLE Users(
	id INT UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(64) NOT NULL, 
	last_name VARCHAR(128) NOT NULL,
	role ENUM('employer', 'inscrit', 'admin'),
	loan_number INT NOT NULL CHECK (loan_number <= 10)
	);

DROP TABLE IF EXISTS Auteur;
CREATE TABLE Auteur(
	uuid VARCHAR(64) UNIQUE NOT NULL PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	last_name VARCHAR(128) NOT NULL,
	birth_date TIMESTAMP,
	death TIMESTAMP,
	current ENUM('humanisme', 'baroque', 'classicisme', 'lumières', 'romantisme', 'réalisme', 'naturalisme', 'symbolisme', 'surréalisme', 'absurde', 'pléiade')
	);