DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Users;
DROP DATABASE IF EXISTS media_db;
DROP USER IF EXISTS Ulna;
DROP TYPE IF EXISTS kindOf;
DROP TYPE IF EXISTS currentOf;
DROP TYPE IF EXISTS roleOf;
CREATE USER Ulna PASSWORD 'radius2';
CREATE DATABASE media_db OWNER Ulna;

CREATE TYPE kindOf AS ENUM('poésie', 'roman', 'théatre', 'épistolaire', 'BD', 'comics', 'dvd', 'cd', 'vinyle', 'livre diver', 'revue');
CREATE TYPE currentOf AS ENUM('humanisme', 'baroque', 'classicisme', 'lumières', 'romantisme', 'réalisme', 'naturalisme', 'symbolisme', 'surréalisme', 'absurde', 'pléiade');
CREATE TYPE roleOf AS ENUM('employer', 'inscrit', 'admin');

CREATE TABLE Users(
	id INT UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	last_name VARCHAR(128) NOT NULL,
	role roleOf,
	loan_number INT NOT NULL CHECK (loan_number <= 10) DEFAULT 0,
	email VARCHAR(64) NOT NULL,
	birth_date TIMESTAMP NOT NULL,
	adresse TEXT NOT NULL,
	mdp VARCHAR(256) NOT NULL,
	is_verified BOOLEAN NOT NULL
	);

CREATE TABLE Author(
	uuid VARCHAR(64) UNIQUE NOT NULL PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	last_name VARCHAR(128) NOT NULL,
	birth_date TIMESTAMP,
	death TIMESTAMP,
	current currentOf
	);

CREATE TABLE Book(
	title VARCHAR(256) UNIQUE NOT NULL PRIMARY KEY,
	image BYTEA NOT NULL,
	release_date TIMESTAMP NOT NULL,
	descrition TEXT NOT NULL,
	author VARCHAR(64) NOT NULL,
	kind kindOf NOT NULL DEFAULT 'livre diver',
	isbn VARCHAR(64) UNIQUE,
	loan_date TIMESTAMP,
	edition VARCHAR(128),
	borrower INT,
	CONSTRAINT fk_Users
		FOREIGN KEY(borrower)
			REFERENCES Users(id),
		FOREIGN KEY(author)
			REFERENCES Author(uuid)
	);