-- DROP TABLE IF EXISTS Book;
-- DROP TABLE IF EXISTS Author;
-- DROP TABLE IF EXISTS Users;
-- DROP DATABASE IF EXISTS media_db;
-- DROP USER IF EXISTS Ulna;
-- DROP TYPE IF EXISTS kindOf;
-- DROP TYPE IF EXISTS currentOf;
-- DROP TYPE IF EXISTS roleOf;

CREATE USER Ulna PASSWORD 'radius2';
CREATE DATABASE media_db OWNER ulna;