-- DROP TABLE IF EXISTS Book;
-- DROP TABLE IF EXISTS Author;
-- DROP TABLE IF EXISTS Users;
-- DROP TYPE IF EXISTS kindOf;
-- DROP TYPE IF EXISTS currentOf;
-- DROP TYPE IF EXISTS roleOf;

CREATE TYPE kindOf AS ENUM('po%C3%A9sie', 'roman', 'th%C3%A9atre', 'jeunesse', 'BD', 'comics', 'dvd', 'cd', 'vinyle', 'livre diver', 'revue');
CREATE TYPE currentOf AS ENUM('humanisme', 'baroque', 'classicisme', 'lumi%C3%A8res', 'romantisme', 'r%C3%A9alisme', 'naturalisme', 'symbolisme', 'surr%C3%A9alisme', 'absurde', 'pl%C3%A9iade');
CREATE TYPE roleOf AS ENUM('employer', 'inscrit', 'admin');

CREATE TABLE Users(
	id INT UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	last_name VARCHAR(128) NOT NULL,
	role roleOf,
	loan_number INT NOT NULL CHECK (loan_number <= 10) DEFAULT 0,
	email VARCHAR(64) NOT NULL UNIQUE,
	birth_date TIMESTAMP NOT NULL,
	adresse TEXT NOT NULL,
	mdp VARCHAR(256) NOT NULL,
	is_verified BOOLEAN NOT NULL
	);

CREATE TABLE Author(
	uuid VARCHAR(64) UNIQUE NOT NULL PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	last_name VARCHAR(128) NOT NULL,
	birth_date TIMESTAMP,
	death TIMESTAMP,
	current currentOf
	);

CREATE TABLE Book(
	title VARCHAR(256) UNIQUE NOT NULL PRIMARY KEY,
	image VARCHAR NOT NULL,
	release_date TIMESTAMP NOT NULL,
	descrition TEXT NOT NULL,
	author VARCHAR(64) NOT NULL,
	kind kindOf NOT NULL DEFAULT 'livre diver',
	tags JSON,
	isbn VARCHAR(64) UNIQUE,
	loan_date TIMESTAMP,
	edition VARCHAR(128),
	borrower INT,
	withdrawal BOOLEAN NOT NULL DEFAULT false,
	CONSTRAINT fk_Users
		FOREIGN KEY(borrower)
			REFERENCES Users(id)
	);