DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Users;
DROP DATABASE IF EXISTS media_db;
DROP TYPE IF EXISTS kindOf;
DROP TYPE IF EXISTS currentOf;
DROP TYPE IF EXISTS roleOf;